package event.agency.management.system.gui;
import event.agency.management.system.eventorganizer;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class AdminGUI extends JFrame {
       private JButton button1, button2, button3, button4,button5,button6;
       private JPanel mainPanel, panel1, panel2, panel3, panel4,panel5,panel6;

    public AdminGUI() {
        // Initialize components
        button1 = new JButton("Add Organizer");
        button2 = new JButton("Remove Organizer");
        button3 = new JButton("Generate report");
        button4 = new JButton("Confirm event");
        button5 = new JButton("View feedbacks");
        button6 = new JButton("Show Event Organizer");

        // Add action listeners to buttons
        button1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                showPanel(panel1);
            }
        });
        button2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                DeleteEventOrganizerGUI gui1 = new DeleteEventOrganizerGUI();
                gui1.setVisible(true);
            }
        });
        button3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                showPanel(panel3);
            }
        });
        button4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                ConfirmEventGui gui1 = new ConfirmEventGui();
                gui1.setVisible(true);
            }
        });
        button5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                ViewFeedbackInterfaceGUI gui1 = new ViewFeedbackInterfaceGUI();
                gui1.setVisible(true);
            }
        });
        button6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ArrayList<eventorganizer> eventOrganizers = new ArrayList<eventorganizer>();    
                eventorganizer eo1=new  eventorganizer();
                eventOrganizers= eo1.showEventOrganizergui();
                ShowEventOrganizerGUI gui = new ShowEventOrganizerGUI(eventOrganizers);
            }
        });

        // Initialize panels
        panel1 = new JPanel();
        panel1.add(new JLabel("Add Organizer"));

        panel2 = new JPanel();
        panel2.add(new JLabel("Remove Organizer"));

        panel3 = new JPanel();
        panel3.add(new JLabel("Generate report"));

        panel4 = new JPanel();
        panel4.add(new JLabel("Confirm event"));
        
        panel5 = new JPanel();
        panel5.add(new JLabel("View feedbacks"));
        
        panel6 = new JPanel();
        panel6.add(new JLabel("Show Event Organizer"));

        // Initialize main panel and add components
        mainPanel = new JPanel(new GridLayout(6, 1));
        mainPanel.add(button1);
        mainPanel.add(button2);
        mainPanel.add(button3);
        mainPanel.add(button4);
        mainPanel.add(button5);
        mainPanel.add(button6);

        // Add main panel to frame
        add(mainPanel);

        // Set frame properties
        setTitle("Admin");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    // Method to show a panel and hide others
    public void showPanel(JPanel panel) {
        mainPanel.setVisible(false);
        panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AdminGUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
