package event.agency.management.system.gui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class BookTicketGUI extends JFrame implements ActionListener {
    private JLabel paymentLabel;
    private JRadioButton cashRadioButton, fawryRadioButton, visaRadioButton;
    private JButton showTicketsButton;

    public BookTicketGUI() {
        // Set up the JFrame
        setTitle("Payment Method Selection");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setResizable(false);
        setLocationRelativeTo(null);

        // Create and add the payment label
        paymentLabel = new JLabel("Select Payment Method:");
        paymentLabel.setHorizontalAlignment(JLabel.CENTER);
        add(paymentLabel, BorderLayout.NORTH);

        // Create and add the payment method radio buttons
        cashRadioButton = new JRadioButton("Cash");
        fawryRadioButton = new JRadioButton("Fawry");
        visaRadioButton = new JRadioButton("Visa");
        ButtonGroup paymentGroup = new ButtonGroup();
        paymentGroup.add(cashRadioButton);
        paymentGroup.add(fawryRadioButton);
        paymentGroup.add(visaRadioButton);
        JPanel paymentPanel = new JPanel(new GridLayout(3, 1));
        paymentPanel.add(cashRadioButton);
        paymentPanel.add(fawryRadioButton);
        paymentPanel.add(visaRadioButton);
        add(paymentPanel, BorderLayout.CENTER);

        // Create and add the show tickets button
        showTicketsButton = new JButton("Show Tickets");
        showTicketsButton.addActionListener(this);
        add(showTicketsButton, BorderLayout.SOUTH);

        // Show the JFrame
        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == showTicketsButton) {
            int paymentMethod = 0;
            if (cashRadioButton.isSelected()) {
                paymentMethod = 1;
            } else if (fawryRadioButton.isSelected()) {
                paymentMethod = 3;
            } else if (visaRadioButton.isSelected()) {
                paymentMethod = 2;
            } else {
                JOptionPane.showMessageDialog(this, "Please select a payment method.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            dispose(); // Close main GUI
            TicketWithCodesGUI gui1 = new TicketWithCodesGUI(); // Create new GUI 1
            gui1.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                new BookTicketGUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
