package event.agency.management.system.gui;
import event.agency.management.system.customer;
import event.agency.management.system.database;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class CreateAccountGUI extends JFrame implements ActionListener {
    private JTextField nameField, phoneField, emailField, ageField, balanceField;
    private JPasswordField passwordField;
    private JButton createButton;
    private JLabel nameLabel, phoneLabel, emailLabel, ageLabel, passwordLabel, balanceLabel;
    database db = new database();
    customer cu = new customer();
    
    public CreateAccountGUI() {
        // Set up the window
        setTitle("Create Account");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Set up the components
        nameField = new JTextField(20);
        phoneField = new JTextField(20);
        emailField = new JTextField(20);
        ageField = new JTextField(20);
        passwordField = new JPasswordField(20);
        balanceField = new JTextField(20);
        createButton = new JButton("Create");
        nameLabel = new JLabel("Name:");
        phoneLabel = new JLabel("Phone Number:");
        emailLabel = new JLabel("Email:");
        ageLabel = new JLabel("Age:");
        passwordLabel = new JLabel("Password:");
        balanceLabel = new JLabel("Balance:");
        
        // Set up the layout
        setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        c.anchor = GridBagConstraints.LINE_END;
        add(nameLabel, c);
        c.gridy++;
        add(phoneLabel, c);
        c.gridy++;
        add(emailLabel, c);
        c.gridy++;
        add(ageLabel, c);
        c.gridy++;
        add(passwordLabel, c);
        c.gridy++;
        add(balanceLabel, c);
        
        c.gridx = 1;
        c.gridy = 0;
        c.anchor = GridBagConstraints.LINE_START;
        add(nameField, c);
        c.gridy++;
        add(phoneField, c);
        c.gridy++;
        add(emailField, c);
        c.gridy++;
        add(ageField, c);
        c.gridy++;
        add(passwordField, c);
        c.gridy++;
        add(balanceField, c);
        
        c.gridx = 0;
        c.gridy++;
        c.gridwidth = 2;
        c.anchor = GridBagConstraints.CENTER;
        add(createButton, c);
        
        // Add action listener to the button
        createButton.addActionListener(this);
        setLocationRelativeTo(null);
    }
    
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == createButton) {
            String customerName = nameField.getText();
            String customerPhone = phoneField.getText();
            String customerEmail = emailField.getText();
            String customerAge = ageField.getText();
            String customerPassword = new String(passwordField.getPassword());
            int customerBalance = Integer.parseInt(balanceField.getText());
            int id = db.IncrementId();
            customer cust = new customer(customerName,customerPhone,customerEmail,customerAge,customerPassword, id,1,customerBalance);
            cu.AddCustomer(cust);
            db.addCustomer(cust);
            
            // Close the window
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
