package event.agency.management.system.gui;
import event.agency.management.system.booking;
import event.agency.management.system.event;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;

public class CustomerGUI extends JFrame {

       private JButton button1, button2, button3, button4;
       private JPanel mainPanel, panel1, panel2, panel3, panel4;

    public CustomerGUI() {
        // Initialize components
        button1 = new JButton("Update Account");
        button2 = new JButton("Book Ticket OR Add to balance OR Refund Money");
        button3 = new JButton("View booking");
        button4 = new JButton("View events");

        // Add action listeners to buttons
        button1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                UpdateAccountGUI gui1 = new UpdateAccountGUI(); // Create new GUI 1
                gui1.setVisible(true);
            }
        });
        button2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                NavigationGUI gui2 = new NavigationGUI(); // Create new GUI 1
                gui2.setVisible(true);
            }
        });
        button3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                ArrayList<booking> booking = new ArrayList<booking>();
                booking B=new  booking();
                booking= B.showbookinglist();
                ViewBookingDetialsGUI gui = new ViewBookingDetialsGUI(booking); // Create new GUI 1
                gui.setVisible(true);
            }
        });
        button4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose(); // Close main GUI
                ArrayList<event> events = new ArrayList<event>();
                event ev=new  event();
                events= ev.showEvents();
                ViewEventsGui gui = new ViewEventsGui(events); // Create new GUI 1
                gui.setVisible(true);
            }
        });

        // Initialize panels
        panel1 = new JPanel();
        panel1.add(new JLabel("Update Account"));

        panel2 = new JPanel();
        panel2.add(new JLabel("Book Ticket OR Add to balance OR Refund Money"));

        panel3 = new JPanel();
        panel3.add(new JLabel("View booking"));

        panel4 = new JPanel();
        panel4.add(new JLabel("View events"));

        // Initialize main panel and add components
        mainPanel = new JPanel(new GridLayout(4, 1));
        mainPanel.add(button1);
        mainPanel.add(button2);
        mainPanel.add(button3);
        mainPanel.add(button4);

        // Add main panel to frame
        add(mainPanel);

        // Set frame properties
        setTitle("Customer");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    // Method to show a panel and hide others
    public void showPanel(JPanel panel) {
        mainPanel.setVisible(false);
        panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CustomerGUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
