package event.agency.management.system.gui;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class MainGUI extends JFrame {

    private JButton button1, button2;
    
    public MainGUI() {
    setTitle("Main GUI");
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    getContentPane().setBackground(new Color(255, 255, 204)); // Set background color
    
    // Create buttons with colors
    button1 = new JButton("Login");
    button1.setBackground(new Color(255, 0, 0));
    button1.setForeground(Color.WHITE);
    button2 = new JButton("Create Account");
    button2.setBackground(new Color(0, 0, 255));
    button2.setForeground(Color.WHITE);

    // Create gridbag layout manager and constraints
    GridBagLayout layout = new GridBagLayout();
    GridBagConstraints c = new GridBagConstraints();
    setLayout(layout);

    // Add button1 to layout
    c.gridx = 0;
    c.gridy = 0;
    c.insets = new Insets(10, 10, 10, 10);
    add(button1, c);

    // Add button2 to layout
    c.gridx = 0;
    c.gridy = 1;
    add(button2, c);

    // Add action listeners to buttons
    button1.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            dispose(); // Close main GUI
            LoginGUI gui1 = new LoginGUI(); // Create new GUI 1
            gui1.setVisible(true); // Show new GUI 1
        }
    });

    button2.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            dispose(); // Close main GUI
            CreateAccountGUI gui2 = new CreateAccountGUI(); // Create new GUI 2
            gui2.setVisible(true); // Show new GUI 2
        }
    });

    pack();
    setLocationRelativeTo(null); // Center GUI on screen
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MainGUI mainGUI = new MainGUI();
        mainGUI.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
